<a href="https://colab.research.google.com/github/poonam-khot/poonam-khot/blob/main/Numpy_Lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy array properties and operations


In [ ]:
import numpy as np

arr = np.array([2,3, 4,5.6, 1])
arr1 = np.array([7,8,"poo",9,10])
arr2 = np.array([[1,2,3,4], [5,6,7,8]])

print(arr.ndim)
print(arr2.ndim)

print(arr.shape)
print(arr2.shape)

print(arr.size)
print(arr1.size)
print(arr2.size)

print(arr.dtype)
print(arr1.dtype)
print(arr2.dtype)

1
2
(5,)
(2, 4)
5
5
8
float64
<U21
int64


In [ ]:
print(arr1.dtype)

<U21


### Typecasting Example

In [3]:
float_arr = np.array([1.1, 2.7, 3.5, 4.9])
print("Original array: %s, dtype: %s" % (float_arr, float_arr.dtype))

# Typecasting to integer
int_arr = float_arr.astype(int)
print("Casted array: %s, dtype: %s" % (int_arr, int_arr.dtype))

# Typecasting to string
str_arr = float_arr.astype(str)
print("Casted array: %s, dtype: %s" % (str_arr, str_arr.dtype))

Original array: [1.1 2.7 3.5 4.9], dtype: float64
Casted array: [1 2 3 4], dtype: int64
Casted array: ['1.1' '2.7' '3.5' '4.9'], dtype: <U32


### Modifying a numeric value in a string array

In [4]:
# Original array with numbers as strings
string_arr = np.array(['10', '20', '30', '40', '50'])
print("Original string array: %s, dtype: %s" % (string_arr, string_arr.dtype))

# Convert to integer array to perform numeric operations
int_arr_temp = string_arr.astype(int)
print("Converted to integer array: %s, dtype: %s" % (int_arr_temp, int_arr_temp.dtype))

# Modify a value (e.g., change the second element)
int_arr_temp[1] = 25
print("Modified integer array: %s, dtype: %s" % (int_arr_temp, int_arr_temp.dtype))

# Convert back to string array
modified_string_arr = int_arr_temp.astype(str)
print("Converted back to string array: %s, dtype: %s" % (modified_string_arr, modified_string_arr.dtype))

Original string array: ['10' '20' '30' '40' '50'], dtype: <U2
Converted to integer array: [10 20 30 40 50], dtype: int64
Modified integer array: [10 25 30 40 50], dtype: int64
Converted back to string array: ['10' '25' '30' '40' '50'], dtype: <U21


### Reason for Typecasting
When you have an array of strings that actually represent numeric values, and you need to perform mathematical operations or comparisons on them, you must first convert them to a numeric type (like `int` or `float`). After performing the desired operations, you can convert them back to strings if the original format is required for display or storage.

### Why can't we perform arithmetic on strings directly?

When you have numeric values stored as strings (e.g., `'10'`, `'20'`), Python (and most programming languages) treats them as sequences of characters, not as numbers. If you try to perform arithmetic operations directly on these string representations, you'll encounter different behaviors:

*   **Concatenation for Addition (`+`):** If you use the `+` operator on two strings, Python will concatenate them (join them together) rather than adding their numeric values. For example, `'10' + '20'` results in `'1020'`, not `30`.

*   **Errors for Other Arithmetic Operations:** For other operations like subtraction (`-`), multiplication (`*`), or division (`/`), attempting to use them directly on strings will typically result in a `TypeError` because these operations are not defined for string operands. Python doesn't know how to 'subtract' or 'multiply' characters.

Therefore, to perform mathematical calculations on numbers that are currently stored as strings, you must first explicitly convert them to a numeric data type (like `int` or `float`) using functions or methods like `int()` or `astype(int)` (for NumPy arrays).

### Understanding `<U2` and `<U21` dtypes in NumPy

When you see `dtype=<U2` or `dtype=<U21` in a NumPy array output, it indicates that the array contains **Unicode strings**.

*   **`<U`**: This part signifies that the data type is a Unicode string.
*   **The number (e.g., `2` or `21`)**: This number indicates the **maximum length of any string element** in the array. NumPy determines this length when the array is created, based on the longest string present.
    *   `dtype=<U2` means that all string elements in the array have a maximum length of 2 characters.
    *   `dtype=<U21` means that all string elements in the array have a maximum length of 21 characters.

NumPy uses a fixed-size string length to optimize memory usage and performance. If you later try to assign a string longer than the defined maximum length to an element in such an array, the string will be truncated to fit the allocated size.

In [5]:
import numpy as np

# Array with strings of max length 2
arr_u2 = np.array(['ab', 'c', 'de'])
print("Array: %s, dtype: %s" % (arr_u2, arr_u2.dtype))

# Array with strings of max length 5
arr_u5 = np.array(['hello', 'world', 'a'])
print("Array: %s, dtype: %s" % (arr_u5, arr_u5.dtype))

# Array with a long string, forcing a larger U-type
arr_u_long = np.array(['short', 'this is a much longer string'])
print("Array: %s, dtype: %s" % (arr_u_long, arr_u_long.dtype))

print("\n--- Demonstrating Truncation ---")
trunc_arr = np.array(['one', 'two'], dtype='<U3') # Explicitly set max length 3
print("Original trunc_arr: %s, dtype: %s" % (trunc_arr, trunc_arr.dtype))

trunc_arr[0] = 'onetwothreefour' # Assign a longer string
print("Truncated trunc_arr: %s, dtype: %s" % (trunc_arr, trunc_arr.dtype))

Array: ['ab' 'c' 'de'], dtype: <U2
Array: ['hello' 'world' 'a'], dtype: <U5
Array: ['short' 'this is a much longer string'], dtype: <U28

--- Demonstrating Truncation ---
Original trunc_arr: ['one' 'two'], dtype: <U3
Truncated trunc_arr: ['one' 'two'], dtype: <U3


### Common NumPy Array Operations

NumPy arrays are highly efficient for numerical operations, supporting a wide range of functionalities. Here are some fundamental operations:

1.  **Arithmetic Operations:** Perform element-wise addition, subtraction, multiplication, and division with scalars or other arrays.
    *   **Syntax:** `array + scalar`, `array * array2`
    *   **Example:** `np.array([1, 2]) + 5` results in `[6, 7]`

2.  **Comparison Operations:** Element-wise comparisons that return a boolean array.
    *   **Syntax:** `array > scalar`, `array == array2`
    *   **Example:** `np.array([1, 5]) > 2` results in `[False, True]`

3.  **Aggregation Functions:** Methods to compute statistics over an array (e.g., sum, mean, min, max, std).
    *   **Syntax:** `array.sum()`, `array.mean(axis=0)`
    *   **Example:** `np.array([1, 2, 3]).sum()` results in `6`

4.  **Indexing and Slicing:** Access specific elements or sub-arrays using integer or boolean indexing, similar to Python lists but with N-dimensional capabilities.
    *   **Syntax:** `array[index]`, `array[start:end:step]`
    *   **Example:** `np.array([10, 20, 30])[1]` results in `20`

5.  **Shape Manipulation:** Changing the dimensions of an array without changing its data.
    *   **Syntax:** `array.reshape(new_shape)`
    *   **Example:** `np.array([1, 2, 3, 4]).reshape(2, 2)` creates a 2x2 array.

Let's see these in action with some code examples.

In [12]:
import numpy as np

# Create example arrays
arr = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_other = np.array([5, 4, 3, 2, 1])

print("Original Array (arr):\n", arr)
print("Original 2D Array (arr_2d):\n", arr_2d)
print("Other Array (arr_other):\n", arr_other)

# --- 1. Arithmetic Operations ---
print("\n--- Arithmetic Operations ---")
print("arr + 10: %s" % (arr + 10)) # Scalar addition (traditional print)
print(f"arr * arr_other: {arr * arr_other}") # Element-wise multiplication (f-string print)
print("arr - arr_other: %s" % (arr - arr_other))

# --- 2. Comparison Operations ---
print("\n--- Comparison Operations ---")
print("arr > 3: %s" % (arr > 3)) # Element-wise comparison
print("arr == arr_other: %s" % (arr == arr_other))

# --- 3. Aggregation Functions ---
print("\n--- Aggregation Functions ---")
print("Sum of arr: %s" % arr.sum())
print("Mean of arr: %.2f" % arr.mean())
print("Max of arr_2d: %s" % arr_2d.max()) # Max of entire 2D array
print("Max along columns of arr_2d (axis=0): %s" % arr_2d.max(axis=0)) # Max of each column
print("Max along rows of arr_2d (axis=1): %s" % arr_2d.max(axis=1)) # Max of each row

# Mean and Standard Deviation for 2D array
print("Mean of arr_2d: %.2f" % arr_2d.mean()) # Mean of entire 2D array
print("Mean along columns of arr_2d (axis=0): %s" % arr_2d.mean(axis=0)) # Mean of each column
print("Mean along rows of arr_2d (axis=1): %s" % arr_2d.mean(axis=1)) # Mean of each row

print("Std Dev of arr_2d: %.2f" % arr_2d.std()) # Standard deviation of entire 2D array
print("Std Dev along columns of arr_2d (axis=0): %s" % arr_2d.std(axis=0)) # Std dev of each column
print("Std Dev along rows of arr_2d (axis=1): %s" % arr_2d.std(axis=1)) # Std dev of each row

# --- 4. Indexing and Slicing ---
print("\n--- Indexing and Slicing ---")
print("Element at index 2 of arr: %s" % arr[2])
print("First two elements of arr: %s" % arr[0:2]) # Slice from index 0 up to (but not including) 2
print("Last element of arr: %s" % arr[-1])
print("Element at row 1, column 0 of arr_2d: %s" % arr_2d[1, 0])
print("First row of arr_2d: %s" % arr_2d[0, :]) # All columns in the first row

# --- 5. Shape Manipulation ---
print("\n--- Shape Manipulation ---")
reshaped_arr = arr.reshape(5, 1) # Reshape to a 5x1 column vector
print("Reshaped arr (5x1):\n%s" % reshaped_arr)
print("Shape of reshaped_arr: %s" % reshaped_arr.shape)

Original Array (arr):
 [1 2 3 4 5]
Original 2D Array (arr_2d):
 [[1 2 3]
 [4 5 6]]
Other Array (arr_other):
 [5 4 3 2 1]

--- Arithmetic Operations ---
arr + 10: [11 12 13 14 15]
arr * arr_other: [5 8 9 8 5]
arr - arr_other: [-4 -2  0  2  4]

--- Comparison Operations ---
arr > 3: [False False False  True  True]
arr == arr_other: [False False  True False False]

--- Aggregation Functions ---
Sum of arr: 15
Mean of arr: 3.00
Max of arr_2d: 6
Max along columns of arr_2d (axis=0): [4 5 6]
Max along rows of arr_2d (axis=1): [3 6]
Mean of arr_2d: 3.50
Mean along columns of arr_2d (axis=0): [2.5 3.5 4.5]
Mean along rows of arr_2d (axis=1): [2. 5.]
Std Dev of arr_2d: 1.71
Std Dev along columns of arr_2d (axis=0): [1.5 1.5 1.5]
Std Dev along rows of arr_2d (axis=1): [0.81649658 0.81649658]

--- Indexing and Slicing ---
Element at index 2 of arr: 3
First two elements of arr: [1 2]
Last element of arr: 5
Element at row 1, column 0 of arr_2d: 4
First row of arr_2d: [1 2 3]

--- Shape Manipulation

TypeError: not all arguments converted during string formatting

### Boolean Indexing in NumPy

Boolean indexing (also known as boolean masking) is a method of selecting elements from a NumPy array based on conditions that result in a boolean array. When a boolean array of the same shape as the original array is used as an index, elements corresponding to `True` in the boolean array are selected, and elements corresponding to `False` are ignored.

This technique is incredibly useful for filtering data, selecting specific subsets of an array, or modifying elements that meet certain criteria.

**How it works:**
1.  You create a boolean array (or mask) by applying a conditional expression to your NumPy array (e.g., `arr > 5`). This results in an array of `True` and `False` values.
2.  You then use this boolean array to index the original array: `original_array[boolean_array]`.
3.  NumPy returns a new array containing only the elements where the boolean mask was `True`.

In [7]:
import numpy as np

# Create a sample NumPy array
numbers = np.array([10, 25, 3, 40, 15, 8, 30])
print("Original array: %s" % numbers)

# --- Example 1: Selecting elements greater than a value ---
# Create a boolean array where elements > 20 are True
mask_gt_20 = numbers > 20
print("\nBoolean mask for > 20: %s" % mask_gt_20)

# Use the boolean mask to select elements
selected_elements_gt_20 = numbers[mask_gt_20]
print("Elements greater than 20: %s" % selected_elements_gt_20)

# --- Example 2: Selecting elements less than or equal to a value ---
mask_le_15 = numbers <= 15
print("\nBoolean mask for <= 15: %s" % mask_le_15)
selected_elements_le_15 = numbers[mask_le_15]
print("Elements less than or equal to 15: %s" % selected_elements_le_15)

# --- Example 3: Combining conditions (logical AND) ---
# Select elements between 10 and 30 (inclusive)
mask_between_10_30 = (numbers >= 10) & (numbers <= 30)
print("\nBoolean mask for between 10 and 30: %s" % mask_between_10_30)
selected_elements_between_10_30 = numbers[mask_between_10_30]
print("Elements between 10 and 30: %s" % selected_elements_between_10_30)

# --- Example 4: Modifying elements using boolean indexing ---
# Double all elements that are less than 10
print("\nArray before modification: %s" % numbers)
numbers[numbers < 10] = numbers[numbers < 10] * 2
print("Array after doubling elements less than 10: %s" % numbers)

Original array: [10 25  3 40 15  8 30]

Boolean mask for > 20: [False  True False  True False False  True]
Elements greater than 20: [25 40 30]

Boolean mask for <= 15: [ True False  True False  True  True False]
Elements less than or equal to 15: [10  3 15  8]

Boolean mask for between 10 and 30: [ True  True False False  True False  True]
Elements between 10 and 30: [10 25 15 30]

Array before modification: [10 25  3 40 15  8 30]
Array after doubling elements less than 10: [10 25  6 40 15 16 30]


### Boolean Indexing in NumPy Explained

Boolean indexing, also known as boolean masking, is a powerful and flexible way to select subsets of data from a NumPy array based on specific conditions. Instead of using integer positions, you provide an array of `True` and `False` values.

**How it works:**

1.  **Create a Boolean Mask:** You define a condition (e.g., `array > value`, `array == another_array`) that, when applied to your NumPy array, results in a new array of the same shape containing `True` where the condition is met and `False` where it is not.
2.  **Apply the Mask:** When this boolean mask is used to index the original array, NumPy returns a new array containing only the elements from the original array where the corresponding value in the boolean mask was `True`.

This method is extremely useful for filtering data, extracting specific records, or modifying elements that satisfy certain criteria without needing explicit loops.

In [8]:
import numpy as np

# Sample array
data = np.array([10, 20, 30, 40, 50, 60, 70])
print("Original Data: %s\n" % data)

# --- Example 1: Basic Filtering ---
# Select elements greater than 40
mask_gt_40 = data > 40
print("Mask (data > 40): %s" % mask_gt_40)
filtered_data = data[mask_gt_40]
print("Elements > 40: %s\n" % filtered_data)

# --- Example 2: Combining Conditions (Logical AND) ---
# Select elements between 20 and 60 (inclusive)
mask_between = (data >= 20) & (data <= 60)
print("Mask (20 <= data <= 60): %s" % mask_between)
selected_range = data[mask_between]
print("Elements between 20 and 60: %s\n" % selected_range)

# --- Example 3: Modifying Elements ---
# Double all elements that are odd (for demonstration, let's say data has some odd numbers)
# Let's create a new array with some odd numbers for this example
new_data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original New Data: %s" % new_data)

# Identify odd numbers
mask_odd = (new_data % 2 != 0)
print("Mask for odd numbers: %s" % mask_odd)

# Modify (double) the odd numbers
new_data[mask_odd] = new_data[mask_odd] * 2
print("New Data after doubling odd numbers: %s" % new_data)

Original Data: [10 20 30 40 50 60 70]

Mask (data > 40): [False False False False  True  True  True]
Elements > 40: [50 60 70]

Mask (20 <= data <= 60): [False  True  True  True  True  True False]
Elements between 20 and 60: [20 30 40 50 60]

Original New Data: [ 1  2  3  4  5  6  7  8  9 10]
Mask for odd numbers: [ True False  True False  True False  True False  True False]
New Data after doubling odd numbers: [ 2  2  6  4 10  6 14  8 18 10]


In [9]:
import numpy as np

# Create a sample array
data = np.array([12, 5, 28, 9, 35, 18, 42, 7])
print("Original Array: %s" % data)

# Create a boolean mask: select elements greater than 20
mask = data > 20
print("Boolean Mask (data > 20): %s" % mask)

# Apply the mask to filter the array
filtered_data = data[mask]
print("Filtered Data (elements > 20): %s" % filtered_data)

# You can also combine conditions, for example, elements between 10 and 30
combined_mask = (data > 10) & (data < 30)
print("\nBoolean Mask (10 < data < 30): %s" % combined_mask)
filtered_data_range = data[combined_mask]
print("Filtered Data (10 < data < 30): %s" % filtered_data_range)

Original Array: [12  5 28  9 35 18 42  7]
Boolean Mask (data > 20): [False False  True False  True False  True False]
Filtered Data (elements > 20): [28 35 42]

Boolean Mask (10 < data < 30): [ True False  True False False  True False False]
Filtered Data (10 < data < 30): [12 28 18]


### Fancy Indexing in NumPy

Fancy indexing (also known as integer array indexing) is a powerful method in NumPy that allows you to select non-contiguous or custom subsets of an array using another array of integers or booleans. Unlike basic indexing and slicing, fancy indexing always returns a *copy* of the data, not a view.

**Key characteristics:**

1.  **Integer Array Indexing:** You can pass an array or list of integers to select specific elements based on their indices. The resulting array will have the same shape as the index array.
    *   Example: `arr[[0, 2, 4]]` selects elements at index 0, 2, and 4.

2.  **Boolean Array Indexing (Boolean Masking):** This is what we just covered. You provide a boolean array of the same shape as the original array, and only elements corresponding to `True` values in the boolean array are selected.
    *   Example: `arr[arr > 5]` selects all elements greater than 5.

Fancy indexing is incredibly useful for reordering data, selecting arbitrary subsets, or extracting rows/columns based on complex conditions.

In [10]:
import numpy as np

# Create a sample 1D array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Original 1D array: %s" % arr)

# --- Example 1: Integer Array Indexing (1D) ---
# Select elements at specific, non-contiguous indices
indices = np.array([0, 3, 7, 2])
fancy_indexed_1d = arr[indices]
print("\nFancy indexed (indices [0, 3, 7, 2]): %s" % fancy_indexed_1d)

# The shape of the result matches the shape of the index array
reordered_indices = np.array([5, 1, 8, 0, 5])
fancy_indexed_reordered = arr[reordered_indices]
print("Fancy indexed (reordered): %s" % fancy_indexed_reordered)

# --- Example 2: Integer Array Indexing (2D) ---
# Create a sample 2D array
arr_2d = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16]
])
print("\nOriginal 2D array:\n%s" % arr_2d)

# Select specific rows
rows_to_select = np.array([0, 2])
selected_rows = arr_2d[rows_to_select]
print("Selected rows (0 and 2):\n%s" % selected_rows)

# Select specific elements (row, column pairs)
# Note: This is different from selecting entire rows/columns
# Here, we want arr_2d[0,1], arr_2d[2,3], arr_2d[1,0]
row_indices = np.array([0, 2, 1])
col_indices = np.array([1, 3, 0])
selected_elements_pairs = arr_2d[row_indices, col_indices]
print("Selected elements (pairs): %s" % selected_elements_pairs)

# --- Example 3: Modifying elements using Fancy Indexing ---
print("\nArray before modification: %s" % arr)
arr[[0, 4, 8]] = [111, 555, 999] # Assign new values to specific indices
print("Array after modification: %s" % arr)

# You can also use boolean arrays for modification (as seen previously)
# For instance, setting all elements greater than 50 to 0
arr[arr > 50] = 0
print("Array after setting elements > 50 to 0: %s" % arr)

Original 1D array: [ 10  20  30  40  50  60  70  80  90 100]

Fancy indexed (indices [0, 3, 7, 2]): [10 40 80 30]
Fancy indexed (reordered): [60 20 90 10 60]

Original 2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Selected rows (0 and 2):
[[ 1  2  3  4]
 [ 9 10 11 12]]
Selected elements (pairs): [ 2 12  5]

Array before modification: [ 10  20  30  40  50  60  70  80  90 100]
Array after modification: [111  20  30  40 555  60  70  80 999 100]
Array after setting elements > 50 to 0: [ 0 20 30 40  0  0  0  0  0  0]


In [1]:
### Reshaping NumPy Arrays

Reshaping a NumPy array means changing the dimensions (shape) of an array while keeping the same data. This is a very common operation, especially when preparing data for machine learning models or when you need to align array structures for various operations.

Key points about reshaping:

*   **Data remains unchanged**: Reshaping only changes how the data is *interpreted* in terms of rows and columns (or higher dimensions), not the actual values within the array.
*   **Total elements must match**: The total number of elements in the original array must be equal to the total number of elements in the reshaped array. For example, a 1D array of 6 elements can be reshaped into a 2x3 or 3x2 2D array, but not a 2x2 array.
*   **`-1` for automatic calculation**: You can use `-1` in one of the dimensions during reshaping, and NumPy will automatically calculate the appropriate size for that dimension based on the total number of elements and the other specified dimensions.

The most common method for reshaping is `array.reshape(new_shape)`.

Let's look at an example:


SyntaxError: invalid decimal literal (61068951.py, line 8)

In [2]:
import numpy as np

# Create a 1D array
arr_1d = np.arange(1, 10)
print("Original 1D array:", arr_1d)
print("Shape of 1D array:", arr_1d.shape)

# --- Reshaping 1D to 2D ---
# Example 1: Reshape into a 3x3 2D array
arr_2d_3x3 = arr_1d.reshape(3, 3)
print("\nReshaped to 3x3 array:\n", arr_2d_3x3)
print("Shape of 3x3 array:", arr_2d_3x3.shape)

# Example 2: Reshape into a 3x? 2D array, let NumPy figure out the second dimension (-1)
arr_2d_3x_auto = arr_1d.reshape(3, -1)
print("\nReshaped to 3x? array (using -1):\n", arr_2d_3x_auto)
print("Shape of 3x? array:", arr_2d_3x_auto.shape)

# Example 3: Reshape into a ?x3 2D array, let NumPy figure out the first dimension (-1)
arr_2d_auto_x3 = arr_1d.reshape(-1, 3)
print("\nReshaped to ?x3 array (using -1):\n", arr_2d_auto_x3)
print("Shape of ?x3 array:", arr_2d_auto_x3.shape)

# --- Reshaping 2D back to 1D (flattening) ---
# You can use reshape(-1) to flatten any array back to a 1D array
arr_flattened = arr_2d_3x3.reshape(-1)
print("\nFlattened array (from 3x3 to 1D):", arr_flattened)
print("Shape of flattened array:", arr_flattened.shape)

# Note: Other methods like .flatten() and .ravel() also flatten arrays:
# arr_flattened_method = arr_2d_3x3.flatten() # Returns a copy
# arr_raveled = arr_2d_3x3.ravel() # Returns a view if possible, otherwise a copy

Original 1D array: [1 2 3 4 5 6 7 8 9]
Shape of 1D array: (9,)

Reshaped to 3x3 array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of 3x3 array: (3, 3)

Reshaped to 3x? array (using -1):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of 3x? array: (3, 3)

Reshaped to ?x3 array (using -1):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of ?x3 array: (3, 3)

Flattened array (from 3x3 to 1D): [1 2 3 4 5 6 7 8 9]
Shape of flattened array: (9,)
